language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t isma/react-test -f client/Dockerfile.dev ./client

script:
  - docker run -e CI=true isma/react-test npm test -- --coverage

after_success:
  - docker build -t isma/multi-client ./client
  - docker build -t isma/multi-nginx ./nginx
  - docker build -t isma/multi-server ./server
  - docker build -t isma/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push isma/multi-client
  - docker push isma/multi-nginx
  - docker push isma/multi-server
  - docker push isma/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-900408709414
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY